apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dlmok5r6i-python
  janus-idp.io/tekton: dlmok5r6i-python
  backstage.io/kubernetes-id: dlmok5r6i-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dlmok5r6i-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
